version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: todo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: todo


  todo:
    image: todoapp:latest
    build: .
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://todo:${MYSQL_PASSWORD}@db/todo
      SECRET_KEY: ${SECRET_KEY}
      MAIL_SERVER: ${MAIL_SERVER}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USE_TLS: ${MAIL_USE_TLS}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}
    ports:
      - "5000:5000"


