"""Add admin column to User table

Revision ID: 1f1421200142
Revises: d58d8e86aa5f
Create Date: 2022-03-24 16:32:13.274190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1421200142'
down_revision = 'd58d8e86aa5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Assign admin status to first registered user.
    op.execute('UPDATE user SET admin=TRUE WHERE id=(SELECT * FROM (SELECT id FROM user ORDER BY id LIMIT 1) AS t);')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
