"""Add reminder table

Revision ID: 7ebdbba54ec7
Revises: 765ee637465c
Create Date: 2022-03-30 12:54:03.478219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebdbba54ec7'
down_revision = '765ee637465c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder',
    sa.Column('id', sa.BINARY(length=16), nullable=False),
    sa.Column('task_id', sa.BINARY(length=16), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('saved_timezone', sa.String(length=100), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    # ### end Alembic commands ###
