"""Add done boolean to tasks

Revision ID: d58d8e86aa5f
Revises: 39912374e89e
Create Date: 2022-03-24 13:49:47.086531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58d8e86aa5f'
down_revision = '39912374e89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'done')
    # ### end Alembic commands ###
