"""Add column for timezone

Revision ID: edae6c54a763
Revises: feef49aab261
Create Date: 2021-09-26 14:01:18.029370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edae6c54a763'
down_revision = 'feef49aab261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('saved_timezone', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'saved_timezone')
    # ### end Alembic commands ###
