"""Add favorite column to task model

Revision ID: feef49aab261
Revises: 9053c5495a16
Create Date: 2021-09-25 13:12:36.839981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feef49aab261'
down_revision = '9053c5495a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'favorite')
    # ### end Alembic commands ###
